apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  creationTimestamp: "2021-10-22T19:16:38Z"
  generation: 1
  labels:
    app: wa3
  name: wa3
  namespace: default
  resourceVersion: "1123"
  uid: 73730204-19bb-4dfe-a5e3-e484bb1b2247
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: wa3
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: wa3
    spec:
      containers:
      - image: w1ckeds1ck/wa3
        imagePullPolicy: Always
        name: wa3
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2021-10-22T19:16:46Z"
    lastUpdateTime: "2021-10-22T19:16:46Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: "2021-10-22T19:16:38Z"
    lastUpdateTime: "2021-10-22T19:16:46Z"
    message: ReplicaSet "wa3-84dd756dbc" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 1
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
