apiVersion : apps/v1
kind: Deployment
metadata:
  name: wa3-deployment
  labels:
    app : wa3
spec:
  replicas: 3
  selector:
    matchLabels:
      project: wa3
  template:
    metadata:
      labels:
        project: wa3
    spec:
      containers:
        - name : wa3
          image: w1ckeds1ck/wa3
          ports:
            - containerPort: 8080
            
---

apiVersion: v1
kind: Service
metadata:
  labels:
    app: wa3
  name: wa3
spec:
  type: ClusterIP
  ports:
  - port: 9999
    protocol: TCP
    targetPort: 8080
  selector:
    app: wa3
